// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client';

type Simplify<T> = {
  [KeyType in keyof T]: T[KeyType];
};
/** Content for about documents */
interface AboutDocumentData {
  /**
   * Slice Zone field in *about*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: about.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/slices
   *
   */
  slices: prismic.SliceZone<AboutDocumentDataSlicesSlice>;
  /**
   * Meta Description field in *about*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: about.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  meta_description: prismic.KeyTextField;
  /**
   * Meta Image field in *about*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  meta_image: prismic.ImageField<never>;
  /**
   * Meta Title field in *about*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: about.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  meta_title: prismic.KeyTextField;
}
/**
 * Slice for *about → Slice Zone*
 *
 */
type AboutDocumentDataSlicesSlice =
  | HeroBannerSlice
  | ArtGallerySlice
  | ThreeItemGridSlice
  | AboutImageTileSlice
  | FeaturedItemsSlice;
/**
 * about document from Prismic
 *
 * - **API ID**: `about`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
  Simplify<AboutDocumentData>,
  'about',
  Lang
>;
/** Content for home documents */
interface HomeDocumentData {
  /**
   * Slice Zone field in *home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/slices
   *
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice>;
  /**
   * Meta Description field in *home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  meta_description: prismic.KeyTextField;
  /**
   * Meta Image field in *home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  meta_image: prismic.ImageField<never>;
  /**
   * Meta Title field in *home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  meta_title: prismic.KeyTextField;
}
/**
 * Slice for *home → Slice Zone*
 *
 */
type HomeDocumentDataSlicesSlice =
  | HeroBannerSlice
  | ThreeItemGridSlice
  | ArtGallerySlice
  | FeaturedItemsSlice;
/**
 * home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
  Simplify<HomeDocumentData>,
  'home',
  Lang
>;
/** Content for nav documents */
interface NavDocumentData {
  /**
   * NavList field in *nav*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: nav.navlist[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/group
   *
   */
  navlist: prismic.GroupField<Simplify<NavDocumentDataNavlistItem>>;
}
/**
 * Item in nav → NavList
 *
 */
export interface NavDocumentDataNavlistItem {
  /**
   * Title field in *nav → NavList*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: nav.navlist[].title
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismic.KeyTextField;
  /**
   * path field in *nav → NavList*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: nav.navlist[].path
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  path: prismic.LinkField;
}
/**
 * nav document from Prismic
 *
 * - **API ID**: `nav`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
  Simplify<NavDocumentData>,
  'nav',
  Lang
>;
/** Content for page documents */
interface PageDocumentData {
  /**
   * Slice Zone field in *page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/slices
   *
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice>;
  /**
   * Meta Description field in *page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  meta_description: prismic.KeyTextField;
  /**
   * Meta Image field in *page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  meta_image: prismic.ImageField<never>;
  /**
   * Meta Title field in *page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  meta_title: prismic.KeyTextField;
}
/**
 * Slice for *page → Slice Zone*
 *
 */
type PageDocumentDataSlicesSlice = HeroBannerSlice;
/**
 * page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
  Simplify<PageDocumentData>,
  'page',
  Lang
>;
/** Content for ProductPage documents */
interface ProductpageDocumentData {
  /**
   * Slice Zone field in *ProductPage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: productpage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/slices
   *
   */
  slices: prismic.SliceZone<ProductpageDocumentDataSlicesSlice>;
  /**
   * Meta Description field in *ProductPage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: productpage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  meta_description: prismic.KeyTextField;
  /**
   * Meta Image field in *ProductPage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: productpage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  meta_image: prismic.ImageField<never>;
  /**
   * Meta Title field in *ProductPage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: productpage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  meta_title: prismic.KeyTextField;
}
/**
 * Slice for *ProductPage → Slice Zone*
 *
 */
type ProductpageDocumentDataSlicesSlice = ProductOrderSlice | ArtGallerySlice | HeroBannerSlice;
/**
 * ProductPage document from Prismic
 *
 * - **API ID**: `productpage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProductpageDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
  Simplify<ProductpageDocumentData>,
  'productpage',
  Lang
>;
/** Content for shop documents */
interface ShopDocumentData {
  /**
   * Slice Zone field in *shop*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: shop.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/slices
   *
   */
  slices: prismic.SliceZone<ShopDocumentDataSlicesSlice>;
  /**
   * Meta Description field in *shop*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: shop.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  meta_description: prismic.KeyTextField;
  /**
   * Meta Image field in *shop*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: shop.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  meta_image: prismic.ImageField<never>;
  /**
   * Meta Title field in *shop*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: shop.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  meta_title: prismic.KeyTextField;
}
/**
 * Slice for *shop → Slice Zone*
 *
 */
type ShopDocumentDataSlicesSlice = never;
/**
 * shop document from Prismic
 *
 * - **API ID**: `shop`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ShopDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
  Simplify<ShopDocumentData>,
  'shop',
  Lang
>;
/** Content for SpecificProductPage documents */
interface SpecificproductpageDocumentData {
  /**
   * Slice Zone field in *SpecificProductPage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: specificproductpage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/slices
   *
   */
  slices: prismic.SliceZone<SpecificproductpageDocumentDataSlicesSlice>;
  /**
   * Meta Description field in *SpecificProductPage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: specificproductpage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  meta_description: prismic.KeyTextField;
  /**
   * Meta Image field in *SpecificProductPage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: specificproductpage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  meta_image: prismic.ImageField<never>;
  /**
   * Meta Title field in *SpecificProductPage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: specificproductpage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  meta_title: prismic.KeyTextField;
}
/**
 * Slice for *SpecificProductPage → Slice Zone*
 *
 */
type SpecificproductpageDocumentDataSlicesSlice =
  | ProductOrderSlice
  | ProductSpecsSlice
  | AboutImageTileSlice
  | FeaturedItemsSlice;
/**
 * SpecificProductPage document from Prismic
 *
 * - **API ID**: `specificproductpage`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SpecificproductpageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<SpecificproductpageDocumentData>,
    'specificproductpage',
    Lang
  >;
export type AllDocumentTypes =
  | AboutDocument
  | HomeDocument
  | NavDocument
  | PageDocument
  | ProductpageDocument
  | ShopDocument
  | SpecificproductpageDocument;
/**
 * Primary content in AboutImageTile → Primary
 *
 */
interface AboutImageTileSliceDefaultPrimary {
  /**
   * img field in *AboutImageTile → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about_image_tile.primary.img
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  img: prismic.ImageField<never>;
  /**
   * heading field in *AboutImageTile → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_image_tile.primary.heading
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  heading: prismic.KeyTextField;
  /**
   * content field in *AboutImageTile → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_image_tile.primary.content
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  content: prismic.RichTextField;
}
/**
 * Item in AboutImageTile → Items
 *
 */
export interface AboutImageTileSliceDefaultItem {
  /**
   * buttonLink field in *AboutImageTile → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: about_image_tile.items[].buttonLink
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  buttonLink: prismic.LinkField;
  /**
   * buttonText field in *AboutImageTile → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_image_tile.items[].buttonText
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  buttonText: prismic.KeyTextField;
}
/**
 * Default variation for AboutImageTile Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type AboutImageTileSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<AboutImageTileSliceDefaultPrimary>,
  Simplify<AboutImageTileSliceDefaultItem>
>;
/**
 * Slice variation for *AboutImageTile*
 *
 */
type AboutImageTileSliceVariation = AboutImageTileSliceDefault;
/**
 * AboutImageTile Shared Slice
 *
 * - **API ID**: `about_image_tile`
 * - **Description**: `AboutImageTile`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type AboutImageTileSlice = prismic.SharedSlice<
  'about_image_tile',
  AboutImageTileSliceVariation
>;
/**
 * Primary content in ArtGallery → Primary
 *
 */
interface ArtGallerySliceDefaultSlicePrimary {
  /**
   * Filter field in *ArtGallery → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: art_gallery.primary.filter
   * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
   *
   */
  filter: prismic.BooleanField;
}
/**
 * Item in ArtGallery → Items
 *
 */
export interface ArtGallerySliceDefaultSliceItem {
  /**
   * image field in *ArtGallery → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: art_gallery.items[].image
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  image: prismic.ImageField<never>;
  /**
   * subtitle field in *ArtGallery → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: art_gallery.items[].subtitle
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  subtitle: prismic.KeyTextField;
  /**
   * title field in *ArtGallery → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: art_gallery.items[].title
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismic.KeyTextField;
  /**
   * type field in *ArtGallery → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: OGILL
   * - **API ID Path**: art_gallery.items[].type
   * - **Documentation**: https://prismic.io/docs/core-concepts/select
   *
   */
  type: prismic.SelectField<'OGILL' | 'Study' | 'Other', 'filled'>;
  /**
   * format field in *ArtGallery → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: default
   * - **API ID Path**: art_gallery.items[].format
   * - **Documentation**: https://prismic.io/docs/core-concepts/select
   *
   */
  format: prismic.SelectField<'default' | 'card-wide' | 'card-tall' | 'card-tall-wide', 'filled'>;
  /**
   * link field in *ArtGallery → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: art_gallery.items[].link
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  link: prismic.ContentRelationshipField;
}
/**
 * Default slice variation for ArtGallery Slice
 *
 * - **API ID**: `default-slice`
 * - **Description**: `ArtGallery`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ArtGallerySliceDefaultSlice = prismic.SharedSliceVariation<
  'default-slice',
  Simplify<ArtGallerySliceDefaultSlicePrimary>,
  Simplify<ArtGallerySliceDefaultSliceItem>
>;
/**
 * Slice variation for *ArtGallery*
 *
 */
type ArtGallerySliceVariation = ArtGallerySliceDefaultSlice;
/**
 * ArtGallery Shared Slice
 *
 * - **API ID**: `art_gallery`
 * - **Description**: `ArtGallery`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ArtGallerySlice = prismic.SharedSlice<'art_gallery', ArtGallerySliceVariation>;
/**
 * Primary content in FeaturedItems → Primary
 *
 */
interface FeaturedItemsSliceDefaultPrimary {
  /**
   * heading field in *FeaturedItems → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_items.primary.heading
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  heading: prismic.RichTextField;
}
/**
 * Item in FeaturedItems → Items
 *
 */
export interface FeaturedItemsSliceDefaultItem {
  /**
   * Here goes the field name field in *FeaturedItems → Items*
   *
   * - **Field Type**: Integration Fields (Catalog: `rooster-forge--rooster_forge_test`)
   * - **Placeholder**: This is the field placeholder...
   * - **API ID Path**: featured_items.items[].promoItem
   * - **Documentation**: https://prismic.io/docs/core-concepts/integration-fields
   *
   */
  promoItem: prismic.IntegrationField;
}
/**
 * Default variation for FeaturedItems Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type FeaturedItemsSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<FeaturedItemsSliceDefaultPrimary>,
  Simplify<FeaturedItemsSliceDefaultItem>
>;
/**
 * Slice variation for *FeaturedItems*
 *
 */
type FeaturedItemsSliceVariation = FeaturedItemsSliceDefault;
/**
 * FeaturedItems Shared Slice
 *
 * - **API ID**: `featured_items`
 * - **Description**: `FeaturedItems`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type FeaturedItemsSlice = prismic.SharedSlice<'featured_items', FeaturedItemsSliceVariation>;
/**
 * Primary content in HeroBanner → Primary
 *
 */
interface HeroBannerSliceDefaultPrimary {
  /**
   * Content field in *HeroBanner → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_banner.primary.content
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  content: prismic.RichTextField;
  /**
   * Promo Image field in *HeroBanner → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_banner.primary.image
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  image: prismic.ImageField<never>;
  /**
   * Background Color field in *HeroBanner → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_banner.primary.background_color
   * - **Documentation**: https://prismic.io/docs/core-concepts/color
   *
   */
  background_color: prismic.ColorField;
}
/**
 * Item in HeroBanner → Items
 *
 */
export interface HeroBannerSliceDefaultItem {
  /**
   * buttonLink field in *HeroBanner → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_banner.items[].button_link
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  button_link: prismic.LinkField;
  /**
   * Button Text field in *HeroBanner → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_banner.items[].button_text
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  button_text: prismic.KeyTextField;
}
/**
 * Default variation for HeroBanner Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeroBannerSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<HeroBannerSliceDefaultPrimary>,
  Simplify<HeroBannerSliceDefaultItem>
>;
/**
 * Slice variation for *HeroBanner*
 *
 */
type HeroBannerSliceVariation = HeroBannerSliceDefault;
/**
 * HeroBanner Shared Slice
 *
 * - **API ID**: `hero_banner`
 * - **Description**: `HeroBanner`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeroBannerSlice = prismic.SharedSlice<'hero_banner', HeroBannerSliceVariation>;
/**
 * Default variation for StaticProductOrder Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ProductOrderSliceDefault = prismic.SharedSliceVariation<
  'default',
  Record<string, never>,
  never
>;
/**
 * Slice variation for *StaticProductOrder*
 *
 */
type ProductOrderSliceVariation = ProductOrderSliceDefault;
/**
 * StaticProductOrder Shared Slice
 *
 * - **API ID**: `product_order`
 * - **Description**: `ProductOrder`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ProductOrderSlice = prismic.SharedSlice<'product_order', ProductOrderSliceVariation>;
/**
 * Primary content in ProductSpecs → Primary
 *
 */
interface ProductSpecsSliceDefaultPrimary {
  /**
   * tecSpecs field in *ProductSpecs → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product_specs.primary.tecspecs
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  tecspecs: prismic.RichTextField;
  /**
   * Image Top Left field in *ProductSpecs → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: product_specs.primary.image0
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  image0: prismic.ImageField<never>;
  /**
   * Image Top Right field in *ProductSpecs → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: product_specs.primary.image1
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  image1: prismic.ImageField<never>;
  /**
   * Image Bottom Left field in *ProductSpecs → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: product_specs.primary.image2
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  image2: prismic.ImageField<never>;
  /**
   * Image Bottom RIght field in *ProductSpecs → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: product_specs.primary.image3
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  image3: prismic.ImageField<never>;
}
/**
 * Item in ProductSpecs → Items
 *
 */
export interface ProductSpecsSliceDefaultItem {
  /**
   * content field in *ProductSpecs → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product_specs.items[].content
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  content: prismic.RichTextField;
}
/**
 * Default variation for ProductSpecs Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ProductSpecsSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<ProductSpecsSliceDefaultPrimary>,
  Simplify<ProductSpecsSliceDefaultItem>
>;
/**
 * Slice variation for *ProductSpecs*
 *
 */
type ProductSpecsSliceVariation = ProductSpecsSliceDefault;
/**
 * ProductSpecs Shared Slice
 *
 * - **API ID**: `product_specs`
 * - **Description**: `ProductSpecs`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ProductSpecsSlice = prismic.SharedSlice<'product_specs', ProductSpecsSliceVariation>;
/**
 * Primary content in ThreeItemGrid → Primary
 *
 */
interface ThreeItemGridSliceDefaultPrimary {
  /**
   * uuid field in *ThreeItemGrid → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: three_item_grid.primary.uuid
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  uuid: prismic.KeyTextField;
  /**
   * Here goes the field name field in *ThreeItemGrid → Primary*
   *
   * - **Field Type**: Integration Fields (Catalog: `rooster-forge--rooster_forge_test`)
   * - **Placeholder**: This is the field placeholder...
   * - **API ID Path**: three_item_grid.primary.itemLarge
   * - **Documentation**: https://prismic.io/docs/core-concepts/integration-fields
   *
   */
  itemLarge: prismic.IntegrationField;
  /**
   * Here goes the field name field in *ThreeItemGrid → Primary*
   *
   * - **Field Type**: Integration Fields (Catalog: `rooster-forge--rooster_forge_test`)
   * - **Placeholder**: This is the field placeholder...
   * - **API ID Path**: three_item_grid.primary.itemTopSmall
   * - **Documentation**: https://prismic.io/docs/core-concepts/integration-fields
   *
   */
  itemTopSmall: prismic.IntegrationField;
  /**
   * Here goes the field name field in *ThreeItemGrid → Primary*
   *
   * - **Field Type**: Integration Fields (Catalog: `rooster-forge--rooster_forge_test`)
   * - **Placeholder**: This is the field placeholder...
   * - **API ID Path**: three_item_grid.primary.itemBottomSmall
   * - **Documentation**: https://prismic.io/docs/core-concepts/integration-fields
   *
   */
  itemBottomSmall: prismic.IntegrationField;
  /**
   * test field in *ThreeItemGrid → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: three_item_grid.primary.test
   * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
   *
   */
  test: prismic.BooleanField;
}
/**
 * Default variation for ThreeItemGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ThreeItemGridSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<ThreeItemGridSliceDefaultPrimary>,
  never
>;
/**
 * Slice variation for *ThreeItemGrid*
 *
 */
type ThreeItemGridSliceVariation = ThreeItemGridSliceDefault;
/**
 * ThreeItemGrid Shared Slice
 *
 * - **API ID**: `three_item_grid`
 * - **Description**: `ThreeItemGrid`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ThreeItemGridSlice = prismic.SharedSlice<
  'three_item_grid',
  ThreeItemGridSliceVariation
>;
declare module '@prismicio/client' {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }
  namespace Content {
    export type {
      AboutDocumentData,
      AboutDocumentDataSlicesSlice,
      AboutDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      HomeDocument,
      NavDocumentData,
      NavDocumentDataNavlistItem,
      NavDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      PageDocument,
      ProductpageDocumentData,
      ProductpageDocumentDataSlicesSlice,
      ProductpageDocument,
      ShopDocumentData,
      ShopDocumentDataSlicesSlice,
      ShopDocument,
      SpecificproductpageDocumentData,
      SpecificproductpageDocumentDataSlicesSlice,
      SpecificproductpageDocument,
      AllDocumentTypes,
      AboutImageTileSliceDefaultPrimary,
      AboutImageTileSliceDefaultItem,
      AboutImageTileSliceDefault,
      AboutImageTileSliceVariation,
      AboutImageTileSlice,
      ArtGallerySliceDefaultSlicePrimary,
      ArtGallerySliceDefaultSliceItem,
      ArtGallerySliceDefaultSlice,
      ArtGallerySliceVariation,
      ArtGallerySlice,
      FeaturedItemsSliceDefaultPrimary,
      FeaturedItemsSliceDefaultItem,
      FeaturedItemsSliceDefault,
      FeaturedItemsSliceVariation,
      FeaturedItemsSlice,
      HeroBannerSliceDefaultPrimary,
      HeroBannerSliceDefaultItem,
      HeroBannerSliceDefault,
      HeroBannerSliceVariation,
      HeroBannerSlice,
      ProductOrderSliceDefault,
      ProductOrderSliceVariation,
      ProductOrderSlice,
      ProductSpecsSliceDefaultPrimary,
      ProductSpecsSliceDefaultItem,
      ProductSpecsSliceDefault,
      ProductSpecsSliceVariation,
      ProductSpecsSlice,
      ThreeItemGridSliceDefaultPrimary,
      ThreeItemGridSliceDefault,
      ThreeItemGridSliceVariation,
      ThreeItemGridSlice
    };
  }
}
