// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from 'next/dynamic';

export const components = {
  about_image_tile: dynamic(() => import('./AboutImageTile')),
  art_gallery: dynamic(() => import('./ArtGallery')),
  featured_items: dynamic(() => import('./FeaturedItems')),
  hero_banner: dynamic(() => import('./HeroBanner')),
  product_order: dynamic(() => import('./StaticProductOrder')),
  product_specs: dynamic(() => import('./ProductSpecs')),
  three_item_grid: dynamic(() => import('./ThreeItemGrid'))
};
